@startuml

title __HELPERS's Class Diagram__\n

  namespace app {
    namespace helpers {
      class app.helpers.Attendance {
          - attended : String
          - className : String
          - hour : String
          - showStudents : Button
          - tcid : int
          - teacherName : String
          - ywd : String
          + Attendance()
          + getAttended()
          + getClassName()
          + getHour()
          + getShowStudents()
          + getTcid()
          + getTeacherName()
          + getYwd()
          + setAttended()
          + setClassName()
          + setHour()
          + setShowStudents()
          + setTcid()
          + setTeacherName()
          + setYwd()
      }
    }
  }
  

  namespace app {
    namespace helpers {
      class app.helpers.Class {
          - delbtn : Button
          - ects : int
          - id : int
          - name : String
          - semestar : int
          - updatebtn : Button
          + Class()
          + getDelbtn()
          + getEcts()
          + getId()
          + getName()
          + getSemestar()
          + getUpdatebtn()
          + setDelbtn()
          + setEcts()
          + setId()
          + setName()
          + setSemestar()
          + setUpdatebtn()
      }
    }
  }
  

  namespace app {
    namespace helpers {
      class app.helpers.Hours {
          - hour : String
          + Hours()
      }
    }
  }
  

  namespace app {
    namespace helpers {
      class app.helpers.StudentList {
          - attended : boolean
          - btn : Button
          - indexNum : String
          - studentName : String
          + StudentList()
          + getBtn()
          + getIndexNum()
          + getStudentName()
          + isAttended()
          + setAttended()
          + setBtn()
          + setIndexNum()
          + setStudentName()
      }
    }
  }
  

  namespace app {
    namespace helpers {
      class app.helpers.Timetable {
          - fri : String
          - hour : String
          - mon : String
          - thur : String
          - tue : String
          - wed : String
          + Timetable()
          + getFri()
          + getHour()
          + getMon()
          + getThur()
          + getTue()
          + getWed()
          + setFri()
          + setHour()
          + setMon()
          + setThur()
          + setTue()
          + setWed()
      }
    }
  }
  

  namespace app {
    namespace helpers {
      class app.helpers.User {
          - br_indexa : String
          - deletebtn : Button
          - email : String
          - firstname : String
          - id : int
          - lastname : String
          - password : String
          - type : String
          - updatebtn : Button
          + User()
          + User()
          + User()
          + getBr_indexa()
          + getDeletebtn()
          + getEmail()
          + getFirstname()
          + getId()
          + getLastname()
          + getPassword()
          + getType()
          + getUpdatebtn()
          {static} + getUsers()
          + setBr_indexa()
          + setDeletebtn()
          + setEmail()
          + setFirstname()
          + setId()
          + setLastname()
          + setPassword()
          + setType()
          + setUpdatebtn()
      }
    }
  }
  

  namespace app {
    namespace helpers {
      class app.helpers.Week {
          - id : int
          - name : String
          - year_id : int
          + Week()
      }
    }
  }
  

  namespace app {
    namespace helpers {
      class app.helpers.Years {
          - id : int
          - name : String
          + Years()
          + getId()
          + getName()
          + setId()
          + setName()
      }
    }
  }
  

  namespace app {
    namespace helpers {
      class app.helpers.dbConnect {
          + getConnection()
          {static} + getInstance()
          - dbConnect()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
